/*
 * Copyright (c) 2022 AccelByte Inc. All Rights Reserved
 * This is licensed software from AccelByte Inc, for limitations
 * and restrictions contact your company contract manager.
 *
 * Code generated. DO NOT EDIT.
 */

package net.accelbyte.sdk.api.iam.operations.users;

import java.io.*;
import java.util.*;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import net.accelbyte.sdk.core.HttpResponseException;
import net.accelbyte.sdk.core.Operation;
import net.accelbyte.sdk.core.util.Helper;

/**
 * PublicForcePlatformLinkV3
 *
 * <p>Force linking user account with platform.
 *
 * <p>If this platform account was already linked to another user account, this endpoint will
 * perform force linking and remove platform from that conflict user, not only from the current
 * request namespace but also include all the enrolled namespaces.
 *
 * <p>If current user have linked to this platform with another platform account (include once
 * linked but it is unlinked now), it will not allow user to perform linking.
 *
 * <p>## Supported platforms:
 *
 * <p>* steam : The platform_tokenâs value is the authentication code returned by Steam.
 *
 * <p>* steamopenid : Steam's user authentication method using OpenID 2.0. The platform_token's
 * value is URL generated by Steam on web authentication
 *
 * <p>* facebook : The platform_tokenâs value is the authorization code returned by Facebook OAuth
 *
 * <p>* google : The platform_tokenâs value is the authorization code returned by Google OAuth
 *
 * <p>* oculus : The platform_tokenâs value is a string composed of Oculus's user ID and the nonce
 * separated by a colon (:).
 *
 * <p>* twitch : The platform_tokenâs value is the authorization code returned by Twitch OAuth.
 *
 * <p>* discord : The platform_tokenâs value is the authorization code returned by Discord OAuth
 *
 * <p>* android : The device_id is the Androidâs device ID
 *
 * <p>* ios : The device_id is the iOSâs device ID.
 *
 * <p>* apple : The platform_tokenâs value is the authorization code returned by Apple OAuth.(We
 * will use this code to generate APP token)
 *
 * <p>* device : Every device that doesânt run Android and iOS is categorized as a device. The
 * device_id is the deviceâs ID.
 *
 * <p>* justice : The platform_tokenâs value is the designated userâs access token.
 *
 * <p>* epicgames : The platform_tokenâs value is an access-token obtained from Epicgames EOS
 * Account Service.
 *
 * <p>* ps4 : The platform_tokenâs value is the authorization code returned by Sony OAuth.
 *
 * <p>* ps5 : The platform_tokenâs value is the authorization code returned by Sony OAuth.
 *
 * <p>* nintendo : The platform_tokenâs value is the authorization code(id_token) returned by
 * Nintendo OAuth.
 *
 * <p>* awscognito : The platform_tokenâs value is the aws cognito access token or id token (JWT).
 *
 * <p>* live : The platform_tokenâs value is xbox XSTS token
 *
 * <p>* xblweb : The platform_tokenâs value is code returned by xbox after login
 *
 * <p>* netflix : The platform_tokenâs value is GAT (Gamer Access Token) returned by Netflix
 * backend
 *
 * <p>* snapchat : The platform_tokenâs value is the authorization code returned by Snapchat
 * OAuth.
 */
@Getter
@Setter
public class PublicForcePlatformLinkV3 extends Operation {
  /** generated field's value */
  private String path =
      "/iam/v3/public/namespaces/{namespace}/users/me/platforms/{platformId}/force";

  private String method = "POST";
  private List<String> consumes = Arrays.asList("application/x-www-form-urlencoded");
  private List<String> produces = Arrays.asList("application/json");
  private String locationQuery = null;

  /** fields as input parameter */
  private String namespace;

  private String platformId;
  private String ticket;

  /**
   * @param namespace required
   * @param platformId required
   * @param ticket required
   */
  @Builder
  // @deprecated 2022-08-29 - All args constructor may cause problems. Use builder instead.
  @Deprecated
  public PublicForcePlatformLinkV3(String namespace, String platformId, String ticket) {
    this.namespace = namespace;
    this.platformId = platformId;
    this.ticket = ticket;

    securities.add("Bearer");
  }

  @Override
  public Map<String, String> getPathParams() {
    Map<String, String> pathParams = new HashMap<>();
    if (this.namespace != null) {
      pathParams.put("namespace", this.namespace);
    }
    if (this.platformId != null) {
      pathParams.put("platformId", this.platformId);
    }
    return pathParams;
  }

  @Override
  public Map<String, Object> getFormParams() {
    Map<String, Object> formDataParams = new HashMap<>();
    if (this.ticket != null) {
      formDataParams.put("ticket", this.ticket);
    }
    return formDataParams;
  }

  @Override
  public boolean isValid() {
    if (this.namespace == null) {
      return false;
    }
    if (this.platformId == null) {
      return false;
    }
    if (this.ticket == null) {
      return false;
    }
    return true;
  }

  public void handleEmptyResponse(int code, String contentType, InputStream payload)
      throws HttpResponseException, IOException {
    if (code != 204) {
      final String json = Helper.convertInputStreamToString(payload);
      throw new HttpResponseException(code, json);
    }
  }
}
